name: CI
on:
  pull_request:
    branches:
      - main
env:
  INSTALL_DIR: /srv/www/civi-zero
  EXTENSION_NAME: rc-base
  TERM: xterm-256color
jobs:
  format:
    name: Check format
    uses: ./.github/workflows/reuse-format.yml
  tests:
    name: Unit tests
    runs-on: ubuntu-20.04
    needs: format
    steps:
      - name: Get civi-zero
        uses: actions/checkout@v3
        with:
          repository: reflexive-communications/civi-zero

      - name: Setup environment
        run: ./bin/prepare.sh

      - name: Install CiviCRM
        run: ./bin/install.sh ${INSTALL_DIR}

      - name: Self checkout
        uses: actions/checkout@v3
        with:
          path: ${{ env.EXTENSION_NAME }}

      - name: Install extensions
        run: ./bin/extension.sh ${INSTALL_DIR} ${EXTENSION_NAME}

      - name: Run unit tests
        run: ./bin/tests.sh ${INSTALL_DIR} ${EXTENSION_NAME}
