name: Check formatting (php-cs-fixer)
on:
  workflow_call:
    inputs:
      params:
        description: Options to 'php-cs-fixer fix'
        type: string
        required: false
        default: .
jobs:
  php-cs-fixer:
    name: Run php-cs-fixer
    runs-on: ubuntu-20.04
    steps:
      - name: Install php-cs-fixer
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: php-cs-fixer:3.21.0

      - name: Self checkout
        uses: actions/checkout@v3

      - name: Check code-style
        run: php-cs-fixer fix ${{ inputs.params }}
