name: Check formatting
on:
  workflow_call:
    inputs:
      php_cs_fixer:
        description: Options to 'php-cs-fixer fix'
        type: string
        required: false
        default: --dry-run -v --allow-risky=yes --rules=@PSR12:risky .
jobs:
  php:
    name: PHP code-style
    uses: es-progress/.github/.github/workflows/php-cs-fixer.yml@main
    with:
      params: ${{ inputs.php_cs_fixer }}
  other:
    name: Other code-style
    uses: es-progress/.github/.github/workflows/prettier.yml@main
    with:
      pattern: '**/*.{js,css,md,yml,json,html}'
