name: Check formatting
on:
  workflow_call:
    inputs:
      php_cs_fixer:
        description: Options to 'php-cs-fixer fix'
        type: string
        required: false
        default: --dry-run -v --rules=@PSR2 .
jobs:
  php:
    name: PHP code-style
    uses: ./.github/workflows/reuse-php-cs-fixer.yml
    with:
      params: ${{ inputs.php_cs_fixer }}
  other:
    name: Other code-style
    uses: es-progress/shell/.github/workflows/reuse-prettier.yml@main
    with:
      pattern: '**/*.{js,css,md,yml,json,html}'
